resource "azurerm_key_vault" "cyclecloud" {
  location                   = var.location
  name                       = substr("${local.naming_token}kv", 0, 24)
  resource_group_name        = azurerm_resource_group.testing.name
  sku_name                   = "standard"
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  tags                       = local.common_tags
  soft_delete_retention_days = 7
  rbac_authorization_enabled = true

  # In private_ip mode the vault is reached exclusively via its private
  # endpoint -- disable public network access entirely. In bastion / public_ip
  # standalone deployments the operator's terraform run hits the data plane
  # over the public endpoint, so leave PNA enabled and gate it via firewall.
  public_network_access_enabled = !local.use_private_ip

  network_acls {
    # private_ip mode: vault is closed to the Internet, ip_rules is unused.
    # Other modes: allow the operator's live public IP plus any configured
    # entries so `terraform plan`/`apply`/`destroy` can reach the data plane
    # even if the caller's egress IP has changed since the last apply (the
    # secret resources do a data-plane Read on every refresh). KV ip_rules
    # accepts both bare IPs and CIDRs; allowed_source_ips normalizes to /32.
    default_action = local.use_private_ip ? "Deny" : "Allow"
    bypass         = "AzureServices"
    ip_rules       = local.use_private_ip ? [] : local.allowed_source_ips
  }
}

# Wait for the caller's "Key Vault Administrator" RBAC assignment to propagate
# before writing secrets. Without this, the data-plane Get/Set calls the
# provider makes can return 403 ForbiddenByRbac for ~30-60s after the
# assignment is created.
resource "time_sleep" "kv_rbac_propagation" {
  create_duration = "60s"
  depends_on      = [azurerm_role_assignment.key_vault]
}

resource "azurerm_key_vault_secret" "private_key" {
  depends_on = [time_sleep.kv_rbac_propagation]

  key_vault_id     = azurerm_key_vault.cyclecloud.id
  name             = "${local.naming_token}-cc-private-key"
  value_wo         = ephemeral.tls_private_key.cyclecloud_ephemeral.private_key_openssh
  value_wo_version = 1
}

resource "azurerm_key_vault_secret" "public_key" {
  depends_on = [time_sleep.kv_rbac_propagation]

  key_vault_id     = azurerm_key_vault.cyclecloud.id
  name             = "${local.naming_token}-cc-public-key"
  value_wo         = ephemeral.tls_public_key.cyclecloud_ephemeral.public_key_openssh
  value_wo_version = 1
}

# CycleCloud web-UI administrator password. Generated by Terraform and stored
# write-only in Key Vault; the VM pulls it back at first boot via its managed
# identity (see scripts/cloud-config.yaml.tftpl).
resource "random_password" "cyclecloud_admin" {
  length           = 24
  special          = true
  override_special = "!@#%^*()-_=+"
}

resource "azurerm_key_vault_secret" "cyclecloud_admin_password" {
  depends_on = [time_sleep.kv_rbac_propagation]

  key_vault_id     = azurerm_key_vault.cyclecloud.id
  name             = "${local.naming_token}-cc-admin-password"
  value_wo         = random_password.cyclecloud_admin.result
  value_wo_version = 1
}

# Read the public key back from Key Vault so it can be used as a non-ephemeral
# input to the VM's admin_ssh_key block (the secret resource above is
# write-only, so its `value` attribute is null).
data "azurerm_key_vault_secret" "public_key" {
  key_vault_id = azurerm_key_vault.cyclecloud.id
  name         = azurerm_key_vault_secret.public_key.name
}